version: "2.1"

services:
  ibeam:
    image: voyz/ibeam
    container_name: ibeam
    env_file:
      - .env
      - .env.ibeam
    ports:
      - "${GATEWAY_PORT}:5000"
    network_mode: bridge # Required due to clientportal.gw IP whitelist
    restart: "no" # Prevents IBEAM_MAX_FAILED_AUTH from being exceeded
